import { Participant, Round, CompetitionConfig } from '../types';

export const DEFAULT_CONFIG: CompetitionConfig = {
  schoolName: 'SD NEGERI 01 BINTANG CERIA',
  competitionTitle: 'LOMBA CERDAS CERMAT SANG JUARA SD 2026',
  competitionSubtitle: 'Ajang Bergengsi Asah Otak, Ketangkasan & Sportivitas Siswa',
  theme: 'cerdas-cermat',
  headmasterName: 'Dra. Hj. Ratna Juwita, M.Pd.',
  judgeName: 'Bapak Ahmad Faisal, S.Pd.',
  date: new Date().toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' }),
  soundEnabled: true,
  quizAnswerKey: ['A', 'C', 'B', 'D', 'A', 'C', 'D', 'B', 'A', 'D'],
  quizPointPerQuestion: 10,
};

export const DEFAULT_ROUNDS: Round[] = [
  {
    id: 'round-1',
    name: 'Babak 1: Soal Wajib',
    description: 'Setiap regu menjawab soal wajib (Benar +100, Salah 0)',
    defaultCorrect: 100,
    defaultWrong: 0,
  },
  {
    id: 'round-2',
    name: 'Babak 2: Soal Lemparan',
    description: 'Soal dialihkan jika regu sebelumnya salah (Benar +100 / +50, Salah 0)',
    defaultCorrect: 100,
    defaultWrong: 0,
  },
  {
    id: 'round-3',
    name: 'Babak 3: Babak Rebutan',
    description: 'Adu cepat memencet bel! Hati-hati salah ada pengurangan nilai (Benar +100, Salah -50)',
    defaultCorrect: 100,
    defaultWrong: -50,
  },
  {
    id: 'round-4',
    name: 'Babak 4: Soal Taruhan / Final',
    description: 'Babak penentuan sang juara sejati (Benar +150, Salah -75)',
    defaultCorrect: 150,
    defaultWrong: -75,
  },
];

export const CERDAS_CERMAT_PARTICIPANTS: Participant[] = [
  {
    id: 'p-1',
    name: 'Regu Garuda (Regu A)',
    members: 'Rizky, Salsa, & Daffa',
    grade: 'Kelas 5A & 5B',
    avatar: '🦅',
    color: 'from-amber-400 to-orange-500',
    totalScore: 450,
    roundScores: { 'round-1': 100, 'round-2': 150, 'round-3': 200 },
    rank: 1,
    previousRank: 1,
    correctAnswers: 5,
    wrongAnswers: 1,
    quizAnswers: { 0: 'A', 1: 'C', 2: 'B', 3: 'D', 4: 'A', 5: 'C', 6: 'D', 7: 'B', 8: 'A', 9: 'D' },
    status: 'active',
  },
  {
    id: 'p-2',
    name: 'Regu Rajawali (Regu B)',
    members: 'Annisa, Dimas, & Kevin',
    grade: 'Kelas 5C',
    avatar: '🦁',
    color: 'from-blue-500 to-indigo-600',
    totalScore: 400,
    roundScores: { 'round-1': 100, 'round-2': 100, 'round-3': 200 },
    rank: 2,
    previousRank: 3,
    correctAnswers: 4,
    wrongAnswers: 0,
    quizAnswers: { 0: 'A', 1: 'C', 2: 'B', 3: 'A', 4: 'A', 5: 'C', 6: 'D', 7: 'B', 8: 'A', 9: 'C' },
    status: 'active',
  },
  {
    id: 'p-3',
    name: 'Regu Elang (Regu C)',
    members: 'Fathir, Putri, & Gilang',
    grade: 'Kelas 4A & 4B',
    avatar: '⚡',
    color: 'from-emerald-400 to-teal-600',
    totalScore: 350,
    roundScores: { 'round-1': 100, 'round-2': 150, 'round-3': 100 },
    rank: 3,
    previousRank: 2,
    correctAnswers: 4,
    wrongAnswers: 1,
    quizAnswers: { 0: 'A', 1: 'C', 2: 'B', 3: 'D', 4: 'B', 5: 'C', 6: 'B', 7: 'B', 8: 'A', 9: 'D' },
    status: 'active',
  },
  {
    id: 'p-4',
    name: 'Regu Merpati (Regu D)',
    members: 'Nabila, Farhan, & Clarissa',
    grade: 'Kelas 6A',
    avatar: '🕊️',
    color: 'from-purple-500 to-pink-600',
    totalScore: 250,
    roundScores: { 'round-1': 100, 'round-2': 100, 'round-3': 50 },
    rank: 4,
    previousRank: 4,
    correctAnswers: 3,
    wrongAnswers: 2,
    quizAnswers: { 0: 'B', 1: 'C', 2: 'B', 3: 'D', 4: 'A', 5: 'A', 6: 'D', 7: 'C', 8: 'A', 9: 'D' },
    status: 'active',
  },
  {
    id: 'p-5',
    name: 'Regu Kancil Cerdik (Regu E)',
    members: 'Bagas, Aurel, & Zidan',
    grade: 'Kelas 6B',
    avatar: '🦊',
    color: 'from-rose-400 to-red-600',
    totalScore: 200,
    roundScores: { 'round-1': 100, 'round-2': 50, 'round-3': 50 },
    rank: 5,
    previousRank: 5,
    correctAnswers: 3,
    wrongAnswers: 3,
    quizAnswers: { 0: 'A', 1: 'B', 2: 'B', 3: 'D', 4: 'C', 5: 'C', 6: 'D', 7: 'B', 8: 'C', 9: 'D' },
    status: 'active',
  },
];

export const RANKING_1_PARTICIPANTS: Participant[] = [
  {
    id: 'r-1',
    name: 'Ahmad Fauzan',
    grade: 'Kelas 5A',
    avatar: '🌟',
    color: 'from-amber-400 to-orange-500',
    totalScore: 90,
    roundScores: {},
    rank: 1,
    previousRank: 1,
    correctAnswers: 9,
    wrongAnswers: 1,
    quizAnswers: {},
    status: 'active',
  },
  {
    id: 'r-2',
    name: 'Siti Nur Aisyah',
    grade: 'Kelas 5B',
    avatar: '🌸',
    color: 'from-pink-500 to-rose-600',
    totalScore: 85,
    roundScores: {},
    rank: 2,
    previousRank: 2,
    correctAnswers: 8,
    wrongAnswers: 1,
    quizAnswers: {},
    status: 'active',
  },
  {
    id: 'r-3',
    name: 'Muhammad Kenzo',
    grade: 'Kelas 6A',
    avatar: '🚀',
    color: 'from-blue-500 to-cyan-600',
    totalScore: 80,
    roundScores: {},
    rank: 3,
    previousRank: 4,
    correctAnswers: 8,
    wrongAnswers: 2,
    quizAnswers: {},
    status: 'active',
  },
  {
    id: 'r-4',
    name: 'Tiara Amanda',
    grade: 'Kelas 4C',
    avatar: '🦋',
    color: 'from-emerald-400 to-teal-600',
    totalScore: 75,
    roundScores: {},
    rank: 4,
    previousRank: 3,
    correctAnswers: 7,
    wrongAnswers: 2,
    quizAnswers: {},
    status: 'active',
  },
  {
    id: 'r-5',
    name: 'Bima Satria',
    grade: 'Kelas 5C',
    avatar: '🐯',
    color: 'from-orange-500 to-red-600',
    totalScore: 70,
    roundScores: {},
    rank: 5,
    previousRank: 5,
    correctAnswers: 7,
    wrongAnswers: 3,
    quizAnswers: {},
    status: 'active',
  },
  {
    id: 'r-6',
    name: 'Zahra Kirana',
    grade: 'Kelas 4A',
    avatar: '👑',
    color: 'from-purple-500 to-indigo-600',
    totalScore: 50,
    roundScores: {},
    rank: 6,
    previousRank: 6,
    correctAnswers: 5,
    wrongAnswers: 4,
    quizAnswers: {},
    status: 'eliminated',
  },
];

export const AVATAR_OPTIONS = ['🦅', '🦁', '⚡', '🕊️', '🦊', '🌟', '🌸', '🚀', '🦋', '🐯', '👑', '🐬', '🏆', '🎯', '🦉', '🐼'];
export const COLOR_OPTIONS = [
  { name: 'Kuning Emas', value: 'from-amber-400 to-orange-500' },
  { name: 'Biru Juara', value: 'from-blue-500 to-indigo-600' },
  { name: 'Hijau Daun', value: 'from-emerald-400 to-teal-600' },
  { name: 'Ungu Prestasi', value: 'from-purple-500 to-pink-600' },
  { name: 'Merah Berani', value: 'from-rose-500 to-red-600' },
  { name: 'Sian Ceria', value: 'from-cyan-400 to-blue-500' },
];
